### ISSUE TITLE
Arduino Nano 

### ISSUE THREAD

**Issue by fgeer** [JanDerogee/TeleJukebox#2]
Hello Jan,

Can I use Arduino Nano instead of the Pro Micro?
Can I play more then 10 numbers?

**Comment by JanDerogee** [comment]
I only used a Pro Micro because I personally prefer that model. The design does not have special functions that require the Pro Micro. Though, the benefit of the Pro Micro is it's USB connector, allowing the entire project to be powered through a simple USB poweradapter. So convenient for development and easy to build as you do not need to worry about power connectors, just use your phone charger.

So to make a long story short, I haven't tried it on a Nano, but it should work.

Can it play more then 10 numbers, well, technically it can IF you modify the code. The number of numbers you can play is technically limitted by the MP3 player and the SD-card. So you could make it to play hundreds of different songs. But it requires you to modify the code to allow for the entry of multiple digits. The only reason it can now play 10 songs, is because it plays the song related to the dialed digit, once dialed, playback begins.

**Comment by fgeer** [comment]
Ok thanks but Nano also have a usb conn. and is cheaper!
